title: MageOps RPM
description: MageOps package repository

baseurl: "/rpm"
url: "https://mageops.github.io"

permalink: pretty
exclude: 
  - "node_modules/"
  - "*.gemspec"
  - "*.gem"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "script/"
  - "LICENSE.txt"
  - "lib/"
  - "bin/"
  - "README.md"
  - "Rakefile"

logo: "/assets/images/just-the-docs.png"
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
aux_links:
  "MageOps RPM on GitHub":
    - "//github.com/mageops/rpm"

footer_content: "Copyright &copy; 2019 <a href=\"https://creativestyle.de\">creativestyle</a>"

color_scheme: nil
#ga_tracking: UA-1234567-89

plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false