os: linux
language: shell

env:
  - _BUILD_PKGS="ocaml"
  - _BUILD_PKGS="awscli amazon-efs-utils varnish-modules-extra varnish-module-accept mageops-release"

jobs:
  allow_failures:
    - env: _BUILD_PKGS="ocaml"

services:
  - docker

before_install:
  - .ci/pull-docker

script:
  - .ci/build-packages
  - .ci/build-release
  - .ci/build-public
  
deploy:
  - provider: releases
    token: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: release/*
    skip_cleanup: true
    cleanup: false
    on:
      tags: true
  - provider: pages:git
    target_branch: gh-pages
    keep_history: false
    verbose: true
    token: $GITHUB_OAUTH_TOKEN
    local_dir: public/
    edge: true
    skip_cleanup: true
    cleanup: false
    on:
      tags: true