os: linux
language: shell

services:
  - docker

before_install:
  - .ci/pull-docker

script:
  - .ci/build-packages
  - .ci/build-release
  - .ci/build-public
  
deploy:
  - provider: releases
    token: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: release/*
    skip_cleanup: true
    cleanup: false
    on:
      tags: true
  - provider: pages:git
    target_branch: gh-pages
    keep_history: false
    verbose: true
    token: $GITHUB_OAUTH_TOKEN
    local_dir: public/
    edge: true
    skip_cleanup: true
    cleanup: false
    on:
      tags: true