sudo: required

services:
  - docker

before_install:
  - docker pull mageops/rpm-build:centos-7

script:
  - >
    docker run 
      --tty
      --volume $(pwd):/root/rpmbuild 
      mageops/rpm-build:centos-7
      awscli
      amazon-efs-utils
      varnish-modules-extra
      varnish-module-accept

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: 
    - buildtree/RPMS/**/*.rpm
    - buildtree/SRPMS/*.src.rpm
  skip_cleanup: true
  on:
    tags: true