os: linux
language: shell

services:
  - docker

before_install:
  - .ci/pull-docker

env:
  - _DOCKER_TAG=mageops/rpm-build:centos-7
  - _PUB_DIR=public
  - _RELEASE_DIR=release
  - _REPO_DIR=repo

script:
  - .ci/build-packages
  - .ci/build-release
  - .ci/build-public
  
deploy:
  - provider: releases
    token: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: $_RELEASE_DIR/*
    skip_cleanup: true
    cleanup: false
    on:
      tags: true
  - provider: pages:git
    target_branch: gh-pages
    keep_history: false
    verbose: true
    token: $GITHUB_OAUTH_TOKEN
    local_dir: $_PUB_DIR
    edge: true
    skip_cleanup: true
    cleanup: false
    on:
      tags: true