os: linux
language: ruby
rvm:
  - 2.6.3

services:
  - docker

cache:
  bundler: true
  directories:
     - cache

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

before_install:
  - openssl aes-256-cbc -K $encrypted_a0f7fc7ded7a_key -iv $encrypted_a0f7fc7ded7a_iv -in rpm-gpg-key.sec.asc.enc -out rpm-gpg-key.sec.asc -d
  - echo -e "machine github.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc
  - .ci/pull-docker
  - gem install bundler

script:
  - set -e
  - .ci/fetch-current-repository
  - .ci/fetch-external-packages
  - .ci/build-packages
  - .ci/build-public
  - .ci/build-release

deploy:
  - provider: releases
    token: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: release/*
    skip_cleanup: true
    cleanup: false
    on:
      tags: true
  - provider: pages
    target_branch: gh-pages
    keep_history: true
    verbose: true
    token: $GITHUB_OAUTH_TOKEN
    local_dir: public/
    edge: true
    skip_cleanup: true
    cleanup: false
    on:
      branch: master
