#!/usr/bin/env bash

set -euo pipefail

DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")"

docker build -t mockbuild:latest "$DIR/.docker"

mkdir -p "$DIR/repo/el/7" "$DIR/repo/el-testing/7"
sudo chown 1000 -R $DIR

docker run --privileged \
    -v "$DIR/repo/el/7":/home/builder/repo:z \
    -v "$DIR/packages":/home/builder/packages:ro \
    --rm \
    mockbuild build-rpm

docker run --privileged \
    -v "$DIR/repo/el-testing/7":/home/builder/repo:z \
    -v "$DIR/packages-testing":/home/builder/packages:ro \
    --rm \
    mockbuild build-rpm

sudo chown $UID -R $DIR
