#!/usr/bin/env bash

source "$(dirname "$0")/_config"

rm -rf "$_RELEASE_DIR"
mkdir -p "$_RELEASE_DIR"

cp -rv "$_PUBLIC_REPO_DIR"/**/*.rpm "$_RELEASE_DIR"

cd "$_RELEASE_DIR"; shasum *.rpm > "$(basename "$_RELEASE_DIR").shasum"; cd "$_PWD"