#!/usr/bin/env bash

set -euo pipefail

DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")"

docker build -t mockbuild:latest "$DIR/.docker"

docker run --privileged \
    -v "$DIR/repo/el/7":/home/builder/repo:z \
    -v "$DIR/packages":/home/builder/packages:ro \
    --rm \
    mockbuild build-rpm
