#!/usr/bin/env bash

set -euo pipefail 

_BUILD_PKGS="${_BUILD_PKGS:-\
    mageops-release \
    varnish-release \
    nginx-release \
    mariadb-release \
    elasticsearch-release \
    rabbitmq-release \
    nodejs-release \
    awscli \
    amazon-efs-utils \
    varnish-modules-extra \
    varnish-module-accept
}"

_DOCKER_TAG="${_DOCKER_TAG:-mageops/rpm-build:centos-7}"

set -x

docker run --name mgs-rpm-builder --tty --volume $(pwd):/root/rpmbuild --env MGS_RPM_GPG_KEY_PASSPHRASE="${MGS_RPM_GPG_KEY_PASSPHRASE}" "$_DOCKER_TAG" --sign --create-repo $_BUILD_PKGS
