#!/usr/bin/env bash

source "$(dirname "$0")/_config"

"$_CI_DIR/build-docker"
"$_CI_DIR/fetch-external-packages"
"$_CI_DIR/build-packages"
"$_CI_DIR/build-release"
"$_CI_DIR/build-public"
"$_CI_DIR/push-docker"

