#!/usr/bin/env bash

export _VERSION_BUMP="${1:-patch}"

source "$(dirname "$0")/_config"

"$_CI_DIR/build-all"

git add . -A
git commit -m "Release $_VERSION_BUMP version bump ($(whoami)@$(hostname))"

curl -s https://raw.githubusercontent.com/tomologic/bump-semver/master/bump.sh | bash -s -- "$_VERSION_BUMP"

git push --tags
git push

