#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/_config"

mkdir -p "$_PUBLIC_DIR/" "$_DOCS_DIR/"

pushd ".jekyll"

pwd

export JEKYLL_ENV=production

bundle install

# Not working on my mac right now /FS
# bundle exec just-the-docs rake search:init
bundle exec jekyll build --config config.yml

# Serve cmd
# bundle exec jekyll serve --config config.yml

popd