#!/usr/bin/env bash

source "$(dirname "$0")/_config"

rm -rf "_EXTERNAL_RPMS_DIR/"

mkdir -p \
    "$_BUILDTREE_RPMS_DIR" \
    "$_EXTERNAL_RPMS_DIR/$_ARCH_DIRNAME" \
    "$_EXTERNAL_RPMS_DIR/$_NOARCH_DIRNAME"


# --- Remi's repo ---

curl -Ls "https://rpms.remirepo.net/enterprise/remi-release-7.rpm" -o "$_EXTERNAL_RPMS_DIR/$_NOARCH_DIRNAME/remi-release-7.noarch.rpm"

# --- MySQL Community Repo ---

curl -Ls "http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm" -o "$_EXTERNAL_RPMS_DIR/$_NOARCH_DIRNAME/mysql-community-release-el7-5.noarch.rpm"
curl -Ls "http://repo.mysql.com/mysql57-community-release-el7-9.noarch.rpm" -o "$_EXTERNAL_RPMS_DIR/$_NOARCH_DIRNAME/mysql57-community-release-7-9.noarch.rpm"

# --- Amazon CloudWatch Agent ---

CWAGENT_VERSION="$(curl -Ls https://s3.amazonaws.com/amazoncloudwatch-agent/info/latest/CWAGENT_VERSION)"
CWAGENT_PACKAGE_NAME="amazon-cloudwatch-agent-$CWAGENT_VERSION.el7.x86_64.rpm"

curl -Ls "https://s3.amazonaws.com/amazoncloudwatch-agent/centos/amd64/latest/amazon-cloudwatch-agent.rpm" -o "$_EXTERNAL_RPMS_DIR/$_ARCH_DIRNAME/$CWAGENT_PACKAGE_NAME"
curl -Ls "https://s3.amazonaws.com/amazoncloudwatch-agent/centos/amd64/latest/amazon-cloudwatch-agent.rpm.sig" -o "$_EXTERNAL_RPMS_DIR/$_ARCH_DIRNAME/$CWAGENT_PACKAGE_NAME.sig"
curl -Ls "https://s3.amazonaws.com/amazoncloudwatch-agent/assets/amazon-cloudwatch-agent.gpg" -o "$_EXTERNAL_RPMS_DIR/$_ARCH_DIRNAME/$CWAGENT_PACKAGE_NAME.gpg"

gpg --import "$_EXTERNAL_RPMS_DIR/$_ARCH_DIRNAME/$CWAGENT_PACKAGE_NAME.gpg"
gpg --verify "$_EXTERNAL_RPMS_DIR/$_ARCH_DIRNAME/$CWAGENT_PACKAGE_NAME.sig" "$_EXTERNAL_RPMS_DIR/$_ARCH_DIRNAME/$CWAGENT_PACKAGE_NAME"


rsync -av "$_EXTERNAL_RPMS_DIR/" "$_BUILDTREE_RPMS_DIR/"
rm -rvf "$_EXTERNAL_RPMS_DIR"