#!/usr/bin/env bash

source "$(dirname "$0")/_config"

rm -rvf "$_REPO_DIRNAME" "$_REPO_GIT_CLONE_DIR"
git clone --depth 1 --single-branch --branch "$_REPO_GIT_BRANCH" "$_REPO_GIT" "$_REPO_GIT_CLONE_DIR"

mv -v "$_REPO_GIT_CLONE_DIR/$_REPO_DIRNAME" "$_REPO_DIRNAME"

rm -rf "$_REPO_GIT_CLONE_DIR"


