#!/usr/bin/env bash

source "$(dirname "$0")/_config"

docker pull "$_DOCKER_TESTING_TAG"
docker run --tty --rm "$_DOCKER_TESTING_TAG" yum -y update

docker build .docker --file .docker/testing.Dockerfile --tag "$_DOCKER_TESTING_TAG" --build-arg "MGS_BUILD_PKGS=$_BUILD_PKGS" --no-cache
docker push "$_DOCKER_TESTING_TAG"