name: CI
on:
  push:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Test build
        run: |
          set -e
          sudo apt update && sudo apt install -y qemu-user-static
          .ci/fetch-current-repository
          sudo chown 1000 -R .
          .ci/build-test
          sudo chown $UID -R .
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    environment: github-pages
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          set -e
          sudo apt update && sudo apt install -y qemu-user-static
          .ci/fetch-current-repository
          sudo chown 1000 -R .
          .ci/build-prod
          sudo chown $UID -R .
          # link newest release for compatibility reasons
          rm -f repo/el/7/mageops-release.noarch.rpm
          ln -r -s repo/el/7/noarch/Packages/mageops-release-7-6.noarch.rpm repo/el/7/mageops-release.noarch.rpm
        env:
          MGS_RPM_GPG_KEY_PASSPHRASE: ${{ secrets.MGS_RPM_GPG_KEY_PASSPHRASE }}
          MGS_RPM_GPG_KEY_PUB: ${{ secrets.MGS_RPM_GPG_KEY_PUB }}
          MGS_RPM_GPG_KEY_SEC: ${{ secrets.MGS_RPM_GPG_KEY_SEC }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Build pages
        run: |
          gem install bundler
          .ci/build-public

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: public
          github_token: ${{ secrets.GITHUB_TOKEN }}
