name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt credentials
        run: |
          openssl aes-256-cbc -K $encrypted_a0f7fc7ded7a_key -iv $encrypted_a0f7fc7ded7a_iv -in rpm-gpg-key.sec.asc.enc -out rpm-gpg-key.sec.asc -d
          echo -e "machine github.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Build
        run: |
          set -e
          gem install bundler
          .ci/pull-docker
          .ci/fetch-current-repository
          .ci/fetch-external-packages
          .ci/build-sources
          .ci/build-packages
          .ci/build-public
          .ci/build-release
        env:
          MGS_RPM_GPG_KEY_PASSPHRASE: ${{ secrets.MGS_RPM_GPG_KEY_PASSPHRASE }}
